export enum WeaponCategory {
    Primary,
    Secondary,
    Knife,
    Grenade,
    Bomb,
    Utility,
}

export const WeaponCategories: Record<string, WeaponCategory> = {
    // Primary weapons
    weapon_ak47: WeaponCategory.Primary,
    weapon_aug: WeaponCategory.Primary,
    weapon_awp: WeaponCategory.Primary,
    weapon_bizon: WeaponCategory.Primary,
    weapon_famas: WeaponCategory.Primary,
    weapon_g3sg1: WeaponCategory.Primary,
    weapon_galilar: WeaponCategory.Primary,
    weapon_m249: WeaponCategory.Primary,
    weapon_m4a1_silencer: WeaponCategory.Primary,
    weapon_m4a1_silencer_off: WeaponCategory.Primary,
    weapon_m4a1: WeaponCategory.Primary,
    weapon_mac10: WeaponCategory.Primary,
    weapon_mag7: WeaponCategory.Primary,
    weapon_mp5sd: WeaponCategory.Primary,
    weapon_mp7: WeaponCategory.Primary,
    weapon_mp9: WeaponCategory.Primary,
    weapon_negev: WeaponCategory.Primary,
    weapon_nova: WeaponCategory.Primary,
    weapon_p90: WeaponCategory.Primary,
    weapon_sawedoff: WeaponCategory.Primary,
    weapon_scar20: WeaponCategory.Primary,
    weapon_sg556: WeaponCategory.Primary,
    weapon_ssg08: WeaponCategory.Primary,
    weapon_ump45: WeaponCategory.Primary,
    weapon_xm1014: WeaponCategory.Primary,

    // Secondary weapons
    weapon_cz75a: WeaponCategory.Secondary,
    weapon_deagle: WeaponCategory.Secondary,
    weapon_elite: WeaponCategory.Secondary,
    weapon_fiveseven: WeaponCategory.Secondary,
    weapon_glock: WeaponCategory.Secondary,
    weapon_hkp2000: WeaponCategory.Secondary,
    weapon_p2000: WeaponCategory.Secondary,
    weapon_p250: WeaponCategory.Secondary,
    weapon_revolver: WeaponCategory.Secondary,
    weapon_tec9: WeaponCategory.Secondary,
    weapon_usp_silencer: WeaponCategory.Secondary,
    weapon_usp_silencer_off: WeaponCategory.Secondary,

    // Knives
    weapon_bayonet: WeaponCategory.Knife,
    weapon_knife: WeaponCategory.Knife,
    weapon_knife_bowie: WeaponCategory.Knife,
    weapon_knife_butterfly: WeaponCategory.Knife,
    weapon_knife_canis: WeaponCategory.Knife,
    weapon_knife_cord: WeaponCategory.Knife,
    weapon_knife_css: WeaponCategory.Knife,
    weapon_knife_falchion: WeaponCategory.Knife,
    weapon_knife_flip: WeaponCategory.Knife,
    weapon_knife_gut: WeaponCategory.Knife,
    weapon_knife_gypsy_jackknife: WeaponCategory.Knife,
    weapon_knife_karambit: WeaponCategory.Knife,
    weapon_knife_kukri: WeaponCategory.Knife,
    weapon_knife_m9_bayonet: WeaponCategory.Knife,
    weapon_knife_outdoor: WeaponCategory.Knife,
    weapon_knife_push: WeaponCategory.Knife,
    weapon_knife_skeleton: WeaponCategory.Knife,
    weapon_knife_stiletto: WeaponCategory.Knife,
    weapon_knife_survival_bowie: WeaponCategory.Knife,
    weapon_knife_t: WeaponCategory.Knife,
    weapon_knife_tactical: WeaponCategory.Knife,
    weapon_knife_twinblade: WeaponCategory.Knife,
    weapon_knife_ursus: WeaponCategory.Knife,
    weapon_knife_widowmaker: WeaponCategory.Knife,

    // Grenades
    weapon_decoy: WeaponCategory.Grenade,
    weapon_firebomb: WeaponCategory.Grenade,
    weapon_flashbang: WeaponCategory.Grenade,
    weapon_frag_grenade: WeaponCategory.Grenade,
    weapon_hegrenade: WeaponCategory.Grenade,
    weapon_incgrenade: WeaponCategory.Grenade,
    weapon_molotov: WeaponCategory.Grenade,
    weapon_smokegrenade: WeaponCategory.Grenade,

    // Bomb
    weapon_c4: WeaponCategory.Bomb,

    // Utility
    weapon_taser: WeaponCategory.Utility,
};