// crafting recipe data
/*
format

{
    id: {name: string, base_block?: boolean, ingredients?: [{id: string, quantity: number}], result?: number}
}
*/
/**
 * @type {Object.<string, {name: string, base_block?: boolean, ingredients?: {id?: string, tag?: string, quantity: number}[], result?: number}>}
 */
export const Blocks = Object.freeze({
    acacia_button: { name: "Acacia Button", ingredients: [{ id: "acacia_planks", quantity: 1 }], result: 1 },
    acacia_door: { name: "Acacia Door", ingredients: [{ id: "acacia_planks", quantity: 6 }], result: 3 },
    acacia_fence: {
        name: "Acacia Fence",
        ingredients: [
            { id: "acacia_planks", quantity: 4 },
            { id: "stick", quantity: 2 },
        ],
        result: 3,
    },
    acacia_fence_gate: {
        name: "Acacia Fence Gate",
        ingredients: [
            { id: "acacia_planks", quantity: 2 },
            { id: "stick", quantity: 4 },
        ],
        result: 1,
    },
    acacia_hanging_sign: {
        name: "Acacia Hanging Sign",
        ingredients: [
            { id: "acacia_log", quantity: 6 },
            { id: "chain", quantity: 2 },
        ],
        result: 6,
    },
    acacia_leaves: { name: "Acacia Leaves", base_block: true },
    acacia_log: { name: "Acacia Log", base_block: true },
    acacia_planks: { name: "Acacia Planks", ingredients: [{ id: "acacia_log", quantity: 1 }], result: 4 },
    acacia_pressure_plate: {
        name: "Acacia Pressure Plate",
        ingredients: [{ id: "acacia_planks", quantity: 2 }],
        result: 1,
    },
    acacia_saplilng: { name: "Acacia Sapling", base_block: true },
    acacia_sign: {
        name: "Acacia Sign",
        ingredients: [
            { id: "acacia_planks", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 3,
    },
    acacia_slab: { name: "Acacia Slab", ingredients: [{ id: "acacia_planks", quantity: 3 }], result: 6 },
    acacia_stairs: { name: "Acacia Stairs", ingredients: [{ id: "acacia_planks", quantity: 6 }], result: 4 },
    acacia_trapdoor: { name: "Acacia Trapdoor", ingredients: [{ id: "acacia_planks", quantity: 6 }], result: 2 },
    acacia_wood: { name: "Acacia Wood", ingredients: [{ id: "acacia_log", quantity: 4 }], result: 3 },
    activator_rail: {
        name: "Activator Rail",
        ingredients: [
            { id: "iron_ingot", quantity: 6 },
            { id: "redstone_torch", quantity: 1 },
            { id: "stick", quantity: 2 },
        ],
        result: 6,
    },
    allium: { name: "Allium", base_block: true },
    amethyst_block: { name: "Block of Amethyst", ingredients: [{ id: "amethyst_shard", quantity: 4 }], result: 1 },
    amethyst_cluster: { name: "Amethyst Cluster", base_block: true },
    ancient_debris: { name: "Ancient Debris", base_block: true },
    andesite: { name: "Andesite", base_block: true },
    andesite_slab: { name: "Andesite Slab", ingredients: [{ id: "andesite", quantity: 3 }], result: 6 },
    andesite_stairs: { name: "Andesite Stairs", ingredients: [{ id: "andesite", quantity: 6 }], result: 4 },
    andesite_wall: { name: "Andesite Wall", ingredients: [{ id: "andesite", quantity: 6 }], result: 6 },
    anvil: {
        name: "Anvil",
        ingredients: [
            { id: "iron_block", quantity: 3 },
            { id: "iron_ingot", quantity: 4 },
        ],
        result: 1,
    },
    azalea: { name: "Azalea", base_block: true },
    azalea_leaves: { name: "Azalea Leaves", base_block: true },
    azure_bluet: { name: "Azure Bluet", base_block: true },
    bamboo: { name: "Bamboo", base_block: true },
    bamboo_block: { name: "Block of Bamboo", ingredients: [{ id: "bamboo", quantity: 9 }], result: 1 },
    bamboo_button: { name: "Bamboo Button", ingredients: [{ id: "bamboo_planks", quantity: 1 }], result: 1 },
    bamboo_door: { name: "Bamboo Door", ingredients: [{ id: "bamboo_planks", quantity: 6 }], result: 3 },
    bamboo_fence: {
        name: "Bamboo Fence",
        ingredients: [
            { id: "bamboo_planks", quantity: 4 },
            { id: "stick", quantity: 2 },
        ],
        result: 3,
    },
    bamboo_fence_gate: {
        name: "Bamboo Fence Gate",
        ingredients: [
            { id: "bamboo_planks", quantity: 2 },
            { id: "stick", quantity: 4 },
        ],
        result: 1,
    },
    bamboo_hanging_sign: {
        name: "Bamboo Hanging Sign",
        ingredients: [
            { id: "bamboo_block", quantity: 6 },
            { id: "chain", quantity: 2 },
        ],
        result: 6,
    },
    bamboo_mosaic: { name: "Bamboo Mosaic", ingredients: [{ id: "bamboo_slab", quantity: 2 }], result: 1 },
    bamboo_mosaic_slab: { name: "Bamboo Mosaic Slab", ingredients: [{ id: "bamboo_mosaic", quantity: 3 }], result: 6 },
    bamboo_mosaic_stairs: {
        name: "Bamboo Mosaic Stairs",
        ingredients: [{ id: "bamboo_mosaic", quantity: 6 }],
        result: 4,
    },
    bamboo_planks: { name: "Bamboo Planks", ingredients: [{ id: "bamboo_block", quantity: 1 }], result: 2 },
    bamboo_pressure_plate: {
        name: "Bamboo Pressure Plate",
        ingredients: [{ id: "bamboo_planks", quantity: 2 }],
        result: 1,
    },
    bamboo_shoot: { name: "Bamboo Shoot", base_block: true },
    bamboo_sign: {
        name: "Bamboo Sign",
        ingredients: [
            { id: "bamboo_planks", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 3,
    },
    bamboo_slab: { name: "Bamboo Slab", ingredients: [{ id: "bamboo_planks", quantity: 3 }], result: 6 },
    bamboo_stairs: { name: "Bamboo Stairs", ingredients: [{ id: "bamboo_planks", quantity: 6 }], result: 4 },
    bamboo_trapdoor: { name: "Bamboo Trapdoor", ingredients: [{ id: "bamboo_planks", quantity: 6 }], result: 2 },
    barrel: {
        name: "Barrel",
        ingredients: [
            { tag: "planks", quantity: 6 },
            { tag: "wood_slabs", quantity: 2 },
        ],
        result: 1,
    },
    barrier: { name: "Barrier", base_block: true },
    basalt: { name: "Basalt", base_block: true },
    beacon: {
        name: "Beacon",
        ingredients: [
            { id: "glass", quantity: 5 },
            { id: "nether_star", quantity: 1 },
            { id: "obsidian", quantity: 3 },
        ],
        result: 1,
    },
    bedrock: { name: "Bedrock", base_block: true },
    bee_nest: { name: "Bee Nest", base_block: true },
    beehive: {
        name: "Beehive",
        ingredients: [
            { tag: "planks", quantity: 6 },
            { id: "honeycomb", quantity: 3 },
        ],
        result: 1,
    },
    beetroots: { name: "Beetroots", ingredients: [{ id: "beetroot_seeds", quantity: 1 }], result: 1 },
    bell: { name: "Bell", base_block: true },
    big_dripleaf: { name: "Big Dripleaf", base_block: true },
    birch_button: { name: "Birch Button", ingredients: [{ id: "birch_planks", quantity: 1 }], result: 1 },
    birch_door: { name: "Birch Door", ingredients: [{ id: "birch_planks", quantity: 6 }], result: 3 },
    birch_fence: {
        name: "Birch Fence",
        ingredients: [
            { id: "birch_planks", quantity: 4 },
            { id: "stick", quantity: 2 },
        ],
        result: 3,
    },
    birch_fence_gate: {
        name: "Birch Fence Gate",
        ingredients: [
            { id: "birch_planks", quantity: 2 },
            { id: "stick", quantity: 4 },
        ],
        result: 1,
    },
    birch_hanging_sign: {
        name: "Birch Hanging Sign",
        ingredients: [
            { id: "birch_log", quantity: 6 },
            { id: "chain", quantity: 2 },
        ],
        result: 6,
    },
    birch_leaves: { name: "Birch Leaves", base_block: true },
    birch_log: { name: "Birch Log", base_block: true },
    birch_planks: { name: "Birch Planks", ingredients: [{ id: "birch_log", quantity: 1 }], result: 4 },
    birch_pressure_plate: {
        name: "Birch Pressure Plate",
        ingredients: [{ id: "birch_planks", quantity: 2 }],
        result: 1,
    },
    birch_saplilng: { name: "Birch Sapling", base_block: true },
    birch_sign: {
        name: "Birch Sign",
        ingredients: [
            { id: "birch_planks", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 3,
    },
    birch_slab: { name: "Birch Slab", ingredients: [{ id: "birch_planks", quantity: 3 }], result: 6 },
    birch_stairs: { name: "Birch Stairs", ingredients: [{ id: "birch_planks", quantity: 6 }], result: 4 },
    birch_trapdoor: { name: "Birch Trapdoor", ingredients: [{ id: "birch_planks", quantity: 6 }], result: 2 },
    birch_wood: { name: "Birch Wood", ingredients: [{ id: "birch_log", quantity: 4 }], result: 3 },
    black_banner: {
        name: "Black Banner",
        ingredients: [
            { id: "black_wool", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 1,
    },
    black_bed: {
        name: "Black Bed",
        ingredients: [
            { id: "black_wool", quantity: 3 },
            { id: "planks", quantity: 3 },
        ],
        result: 1,
    },
    black_candle: {
        name: "Black Candle",
        ingredients: [
            { id: "black_dye", quantity: 1 },
            { id: "candle", quantity: 1 },
        ],
        result: 1,
    },
    black_carpet: { name: "Black Carpet", ingredients: [{ id: "black_wool", quantity: 2 }], result: 3 },
    black_concrete: { name: "Black Concrete", ingredients: [{ id: "black_concrete_powder", quantity: 1 }], result: 1 },
    black_concrete_powder: {
        name: "Black Concrete Powder",
        ingredients: [
            { id: "black_dye", quantity: 1 },
            { id: "gravel", quantity: 4 },
            { id: "sand", quantity: 4 },
        ],
        result: 8,
    },
    black_glazed_terracotta: {
        name: "Black Glazed Terracotta",
        ingredients: [{ id: "black_terracotta", quantity: 1 }],
        result: 1,
    },
    black_shulker_box: {
        name: "Black Shulker Box",
        ingredients: [
            { id: "black_dye", quantity: 1 },
            { tag: "shulker_box", quantity: 1 },
        ],
        result: 1,
    },
    black_stained_glass: {
        name: "Black Stained Glass",
        ingredients: [
            { id: "black_dye", quantity: 1 },
            { id: "glass", quantity: 8 },
        ],
        result: 8,
    },
    black_stained_glass_pane: {
        name: "Black Stained Glass Pane",
        ingredients: [
            { id: "black_dye", quantity: 1 },
            { id: "glass_pane", quantity: 8 },
        ],
        result: 8,
    },
    black_terractotta: {
        name: "Black Terracotta",
        ingredients: [
            { id: "black_dye", quantity: 1 },
            { id: "terracotta", quantity: 8 },
        ],
        result: 8,
    },
    black_wool: {
        name: "Black Wool",
        ingredients: [
            { id: "black_dye", quantity: 1 },
            { tag: "wool", quantity: 1 },
        ],
        result: 1,
    },
    blackstone: { name: "Blackstone", base_block: true },
    blackstone_slab: { name: "Blackstone Slab", ingredients: [{ id: "blackstone", quantity: 3 }], result: 6 },
    blackstone_stairs: { name: "Blackstone Stairs", ingredients: [{ id: "blackstone", quantity: 6 }], result: 4 },
    blackstone_wall: { name: "Blackstone Wall", ingredients: [{ id: "blackstone", quantity: 6 }], result: 6 },
    blast_furnace: {
        name: "Blast Furnace",
        ingredients: [
            { id: "furnace", quantity: 1 },
            { id: "iron_ingot", quantity: 5 },
            { id: "smooth_stone", quantity: 3 },
        ],
        result: 1,
    },
    // todo: resource blocks
    blue_banner: {
        name: "Blue Banner",
        ingredients: [
            { id: "blue_wool", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 1,
    },
    blue_bed: {
        name: "Blue Bed",
        ingredients: [
            { id: "blue_wool", quantity: 3 },
            { tag: "planks", quantity: 3 },
        ],
        result: 1,
    },
    blue_candle: {
        name: "Blue Candle",
        ingredients: [
            { id: "blue_dye", quantity: 1 },
            { id: "candle", quantity: 1 },
        ],
        result: 1,
    },
    blue_carpet: { name: "Blue Carpet", ingredients: [{ id: "blue_wool", quantity: 2 }], result: 3 },
    blue_concrete: { name: "Blue Concrete", ingredients: [{ id: "blue_concrete_powder", quantity: 1 }], result: 1 },
    blue_concrete_powder: {
        name: "Blue Concrete Powder",
        ingredients: [
            { id: "blue_dye", quantity: 1 },
            { id: "gravel", quantity: 4 },
            { id: "sand", quantity: 4 },
        ],
        result: 8,
    },
    blue_glazed_terracotta: {
        name: "Blue Glazed Terracotta",
        ingredients: [{ id: "blue_terracotta", quantity: 1 }],
        result: 1,
    },
    blue_ice: { name: "Blue Ice", base_block: true },
    blue_orchid: { name: "Blue Orchid", base_block: true },
    blue_shulker_box: {
        name: "Blue Shulker Box",
        ingredients: [
            { id: "blue_dye", quantity: 1 },
            { tag: "shulker_box", quantity: 1 },
        ],
        result: 1,
    },
    blue_stained_glass: {
        name: "Blue Stained Glass",
        ingredients: [
            { id: "blue_dye", quantity: 1 },
            { id: "glass", quantity: 8 },
        ],
        result: 8,
    },
    blue_stained_glass_pane: {
        name: "Blue Stained Glass Pane",
        ingredients: [
            { id: "blue_dye", quantity: 1 },
            { id: "glass_pane", quantity: 8 },
        ],
        result: 8,
    },
    blue_terracotta: {
        name: "Blue Terracotta",
        ingredients: [
            { id: "blue_dye", quantity: 1 },
            { id: "terracotta", quantity: 8 },
        ],
        result: 8,
    },
    blue_wool: {
        name: "Blue Wool",
        ingredients: [
            { id: "blue_dye", quantity: 1 },
            { tag: "wool", quantity: 1 },
        ],
        result: 1,
    },
    bone_block: { name: "Bone Block", ingredients: [{ id: "bone_meal", quantity: 9 }], result: 1 },
    bookshelf: {
        name: "Bookshelf",
        ingredients: [
            { id: "book", quantity: 3 },
            { tag: "planks", quantity: 6 },
        ],
        result: 1,
    },
    brain_coral: { name: "Brain Coral", base_block: true },
    brain_coral_block: { name: "Brain Coral Block", base_block: true },
    brain_coral_fan: { name: "Brain Coral Fan", base_block: true },
    brewing_stand: {
        name: "Brewing Stand",
        ingredients: [
            { id: "blaze_rod", quantity: 1 },
            { tag: "cobblestone", quantity: 3 },
        ],
        result: 1,
    },
    brick_slab: { name: "Brick Slab", ingredients: [{ id: "brick", quantity: 3 }], result: 6 },
    brick_stairs: { name: "Brick Stairs", ingredients: [{ id: "brick", quantity: 6 }], result: 4 },
    brick_wall: { name: "Brick Wall", ingredients: [{ id: "brick", quantity: 6 }], result: 6 },
    bricks: { name: "Bricks", ingredients: [{ id: "brick", quantity: 4 }], result: 1 },
    brown_banner: {
        name: "Brown Banner",
        ingredients: [
            { id: "brown_wool", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 1,
    },
    brown_bed: {
        name: "Brown Bed",
        ingredients: [
            { id: "brown_wool", quantity: 3 },
            { tag: "planks", quantity: 3 },
        ],
        result: 1,
    },
    brown_candle: {
        name: "Brown Candle",
        ingredients: [
            { id: "brown_dye", quantity: 1 },
            { id: "candle", quantity: 1 },
        ],
        result: 1,
    },
    brown_carpet: { name: "Brown Carpet", ingredients: [{ id: "brown_wool", quantity: 2 }], result: 3 },
    brown_concrete: { name: "Brown Concrete", ingredients: [{ id: "brown_concrete_powder", quantity: 1 }], result: 1 },
    brown_concrete_powder: {
        name: "Brown Concrete Powder",
        ingredients: [
            { id: "brown_dye", quantity: 1 },
            { id: "gravel", quantity: 4 },
            { id: "sand", quantity: 4 },
        ],
        result: 8,
    },
    brown_glazed_terracotta: {
        name: "Brown Glazed Terracotta",
        ingredients: [{ id: "brown_terracotta", quantity: 1 }],
        result: 1,
    },
    brown_mushroom: { name: "Brown Mushroom", base_block: true },
    brown_mushroom_block: { name: "Brown Mushroom Block", base_block: true },
    brown_shulker_box: {
        name: "Brown Shulker Box",
        ingredients: [
            { id: "brown_dye", quantity: 1 },
            { tag: "shulker_box", quantity: 1 },
        ],
        result: 1,
    },
    brown_stained_glass: {
        name: "Brown Stained Glass",
        ingredients: [
            { id: "brown_dye", quantity: 1 },
            { id: "glass", quantity: 8 },
        ],
        result: 8,
    },
    brown_stained_glass_pane: {
        name: "Brown Stained Glass Pane",
        ingredients: [
            { id: "brown_dye", quantity: 1 },
            { id: "glass_pane", quantity: 8 },
        ],
        result: 8,
    },
    brown_terracotta: {
        name: "Brown Terracotta",
        ingredients: [
            { id: "brown_dye", quantity: 1 },
            { id: "terracotta", quantity: 8 },
        ],
        result: 8,
    },
    brown_wool: {
        name: "Brown Wool",
        ingredients: [
            { id: "brown_dye", quantity: 1 },
            { tag: "wool", quantity: 1 },
        ],
        result: 1,
    },
    bubble_coral: { name: "Bubble Coral", base_block: true },
    bubble_coral_block: { name: "Bubble Coral Block", base_block: true },
    bubble_coral_fan: { name: "Bubble Coral Fan", base_block: true },
    budding_amethyst: { name: "Budding Amethyst", base_block: true },
    cactus: { name: "Cactus", base_block: true },
    cake: {
        name: "Cake",
        ingredients: [
            { id: "egg", quantity: 1 },
            { id: "milk_bucket", quantity: 3 },
            { id: "sugar", quantity: 2 },
            { id: "wheat", quantity: 3 },
        ],
        result: 1,
    },
    calcite: { name: "Calcite", base_block: true },
    calibrated_sculk_sensor: {
        name: "Calibrated Sculk Sensor",
        ingredients: [
            { id: "amethyst_shard", quantity: 3 },
            { id: "sculk_sensor", quantity: 1 },
        ],
        result: 1,
    },
    campfire: {
        name: "Campfire",
        ingredients: [
            { id: "charcoal", quantity: 1 },
            { id: "stick", quantity: 3 },
            { tag: "wood", quantity: 3 },
        ],
        result: 1,
    },
    candle: {
        name: "Candle",
        ingredients: [
            { id: "honeycomb", quantity: 1 },
            { id: "string", quantity: 1 },
        ],
        result: 4,
    },
    carrots: { name: "Carrots", ingredients: [{ id: "carrot", quantity: 1 }], result: 1 },
    cartography_table: {
        name: "Cartography Table",
        ingredients: [
            { id: "paper", quantity: 2 },
            { tag: "planks", quantity: 4 },
        ],
        result: 1,
    },
    carved_pumpkin: { name: "Carved Pumpkin", ingredients: [{ id: "pumpkin", quantity: 1 }], result: 1 },
    cauldron: {
        name: "Cauldron",
        ingredients: [{ id: "iron_ingot", quantity: 7 }],
        result: 1,
    },
    cave_vines: { name: "Cave Vines", base_block: true },
    chain: {
        name: "Chain",
        ingredients: [
            { id: "iron_ingot", quantity: 1 },
            { id: "iron_nugget", quantity: 2 },
        ],
        result: 1,
    },
    chain_command_block: { name: "Chain Command Block", base_block: true },
    chest: {
        name: "Chest",
        ingredients: [{ tag: "planks", quantity: 8 }],
        result: 1,
    },
    cherry_button: { name: "Cherry Button", ingredients: [{ id: "cherry_planks", quantity: 1 }], result: 1 },
    cherry_door: { name: "Cherry Door", ingredients: [{ id: "cherry_planks", quantity: 6 }], result: 3 },
    cherry_fence: {
        name: "Cherry Fence",
        ingredients: [
            { id: "cherry_planks", quantity: 4 },
            { id: "stick", quantity: 2 },
        ],
        result: 3,
    },
    cherry_fence_gate: {
        name: "Cherry Fence Gate",
        ingredients: [
            { id: "cherry_planks", quantity: 2 },
            { id: "stick", quantity: 4 },
        ],
        result: 1,
    },
    cherry_hanging_sign: {
        name: "Cherry Hanging Sign",
        ingredients: [
            { id: "cherry_log", quantity: 6 },
            { id: "chain", quantity: 2 },
        ],
        result: 6,
    },
    cherry_leaves: { name: "Cherry Leaves", base_block: true },
    cherry_log: { name: "Cherry Log", base_block: true },
    cherry_planks: { name: "Cherry Planks", ingredients: [{ id: "cherry_log", quantity: 1 }], result: 4 },
    cherry_pressure_plate: {
        name: "Cherry Pressure Plate",
        ingredients: [{ id: "cherry_planks", quantity: 2 }],
        result: 1,
    },
    cherry_saplilng: { name: "Cherry Sapling", base_block: true },
    cherry_sign: {
        name: "Cherry Sign",
        ingredients: [
            { id: "cherry_planks", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 3,
    },
    cherry_slab: { name: "Cherry Slab", ingredients: [{ id: "cherry_planks", quantity: 3 }], result: 6 },
    cherry_stairs: { name: "Cherry Stairs", ingredients: [{ id: "cherry_planks", quantity: 6 }], result: 4 },
    cherry_trapdoor: { name: "Cherry Trapdoor", ingredients: [{ id: "cherry_planks", quantity: 6 }], result: 2 },
    cherry_wood: { name: "Cherry Wood", ingredients: [{ id: "cherry_log", quantity: 4 }], result: 3 },
    chest_minecart: {
        name: "Minecart with Chest",
        ingredients: [
            { id: "chest", quantity: 1 },
            { id: "minecart", quantity: 1 },
        ],
        result: 1,
    },
    chiseled_bookshelf: {
        name: "Chiseled Bookshelf",
        ingredients: [
            { tag: "planks", quantity: 6 },
            { tag: "wood_slabs", quantity: 3 },
        ],
        result: 1,
    },
    chiseled_deepslate: {
        name: "Chiseled Deepslate",
        ingredients: [{ id: "cobbled_deepslate_slab", quantity: 2 }],
        result: 1,
    },
    chiseled_nether_bricks: {
        name: "Chiseled Nether Bricks",
        ingredients: [{ id: "nether_brick_slab", quantity: 2 }],
        result: 1,
    },
    chiseled_polished_blackstone: {
        name: "Chiseled Polished Blackstone",
        ingredients: [{ id: "polished_blackstone_slab", quantity: 2 }],
        result: 1,
    },
    chiseled_quartz_block: {
        name: "Chiseled Quartz Block",
        ingredients: [{ id: "quartz_slab", quantity: 2 }],
        result: 1,
    },
    chiseled_red_sandstone: {
        name: "Chiseled Red Sandstone",
        ingredients: [{ id: "red_sandstone_slab", quantity: 2 }],
        result: 1,
    },
    chiseled_sandstone: {
        name: "Chiseled Sandstone",
        ingredients: [{ id: "sandstone_slab", quantity: 2 }],
        result: 1,
    },
    chiseled_stone_bricks: {
        name: "Chiseled Stone Bricks",
        ingredients: [{ id: "stone_brick_slab", quantity: 2 }],
        result: 1,
    },
    chorus_flower: { name: "Chorus Flower", base_block: true },
    chorus_plant: { name: "Chorus Plant", base_block: true },
    clay: { name: "Clay", base_block: true },
    coal_block: { name: "Block of Coal", ingredients: [{ id: "coal", quantity: 9 }], result: 1 },
    coal_ore: { name: "Coal Ore", base_block: true },
    coarse_dirt: { name: "Coarse Dirt", base_block: true },
    cobbled_deepslate: { name: "Cobbled Deepslate", base_block: true },
    cobbled_deepslate_slab: {
        name: "Cobbled Deepslate Slab",
        ingredients: [{ id: "cobbled_deepslate", quantity: 3 }],
        result: 6,
    },
    cobbled_deepslate_stairs: {
        name: "Cobbled Deepslate Stairs",
        ingredients: [{ id: "cobbled_deepslate", quantity: 6 }],
        result: 4,
    },
    cobbled_deepslate_wall: {
        name: "Cobbled Deepslate Wall",
        ingredients: [{ id: "cobbled_deepslate", quantity: 6 }],
        result: 6,
    },
    cobblestone: { name: "Cobblestone", base_block: true },
    cobblestone_slab: { name: "Cobblestone Slab", ingredients: [{ id: "cobblestone", quantity: 3 }], result: 6 },
    cobblestone_stairs: { name: "Cobblestone Stairs", ingredients: [{ id: "cobblestone", quantity: 6 }], result: 4 },
    cobblestone_wall: { name: "Cobblestone Wall", ingredients: [{ id: "cobblestone", quantity: 6 }], result: 6 },
    cobweb: { name: "Cobweb", base_block: true },
    cocoa: { name: "Cocoa", base_block: true },
    command_block: { name: "Command Block", base_block: true },
    composter: {
        name: "Composter",
        ingredients: [{ tag: "wood_slabs", quantity: 7 }],
        result: 1,
    },
    conduit: {
        name: "Conduit",
        ingredients: [
            { id: "heart_of_the_sea", quantity: 1 },
            { id: "nautilus_shell", quantity: 8 },
        ],
        result: 1,
    },
    copper_block: { name: "Block of Copper", ingredients: [{ id: "copper_ingot", quantity: 9 }], result: 1 },
    copper_ore: { name: "Copper Ore", base_block: true },
    cornflower: { name: "Cornflower", base_block: true },
    cracked_deepslate_bricks: {
        name: "Cracked Deepslate Bricks",
        ingredients: [{ id: "deepslate_bricks", quantity: 1 }],
        result: 1,
    },
    cracked_deepslate_tiles: {
        name: "Cracked Deepslate Tiles",
        ingredients: [{ id: "deepslate_tiles", quantity: 1 }],
        result: 1,
    },
    cracked_nether_bricks: {
        name: "Cracked Nether Bricks",
        ingredients: [{ id: "nether_bricks", quantity: 1 }],
        result: 1,
    },
    cracked_polished_blackstone_bricks: {
        name: "Cracked Polished Blackstone Bricks",
        ingredients: [{ id: "polished_blackstone_bricks", quantity: 1 }],
        result: 1,
    },
    cracked_stone_bricks: {
        name: "Cracked Stone Bricks",
        ingredients: [{ id: "stone_bricks", quantity: 1 }],
        result: 1,
    },
    crafter: {
        name: "Crafter",
        ingredients: [
            { id: "crafting_table", quantity: 1 },
            { id: "dropper", quantity: 1 },
            { id: "iron_ingot", quantity: 5 },
            { id: "redstone", quantity: 2 },
        ],
        result: 1,
    },
    crafting_table: {
        name: "Crafting Table",
        ingredients: [{ tag: "planks", quantity: 4 }],
        result: 1,
    },
    creeper_head: { name: "Creeper Head", base_block: true },
    crimson_button: { name: "Crimson Button", ingredients: [{ id: "crimson_planks", quantity: 1 }], result: 1 },
    crimson_door: { name: "Crimson Door", ingredients: [{ id: "crimson_planks", quantity: 6 }], result: 3 },
    crimson_fence: {
        name: "Crimson Fence",
        ingredients: [
            { id: "crimson_planks", quantity: 4 },
            { id: "stick", quantity: 2 },
        ],
        result: 3,
    },
    crimson_fence_gate: {
        name: "Crimson Fence Gate",
        ingredients: [
            { id: "crimson_planks", quantity: 2 },
            { id: "stick", quantity: 4 },
        ],
        result: 1,
    },
    crimson_fungus: { name: "Crimson Fungus", base_block: true },
    crimson_hanging_sign: {
        name: "Crimson Hanging Sign",
        ingredients: [
            { id: "crimson_stem", quantity: 6 },
            { id: "chain", quantity: 2 },
        ],
        result: 6,
    },
    crimson_hyphae: { name: "Crimson Hyphae", base_block: true },
    crimson_nylium: { name: "Crimson Nylium", base_block: true },
    crimson_planks: { name: "Crimson Planks", ingredients: [{ id: "crimson_stem", quantity: 1 }], result: 4 },
    crimson_pressure_plate: {
        name: "Crimson Pressure Plate",
        ingredients: [{ id: "crimson_planks", quantity: 2 }],
        result: 1,
    },
    crimson_roots: { name: "Crimson Roots", base_block: true },
    crimson_sign: {
        name: "Crimson Sign",
        ingredients: [
            { id: "crimson_planks", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 3,
    },
    crimson_slab: { name: "Crimson Slab", ingredients: [{ id: "crimson_planks", quantity: 3 }], result: 6 },
    crimson_stairs: { name: "Crimson Stairs", ingredients: [{ id: "crimson_planks", quantity: 6 }], result: 4 },
    crimson_stem: { name: "Crimson Stem", base_block: true },
    crimson_trapdoor: { name: "Crimson Trapdoor", ingredients: [{ id: "crimson_planks", quantity: 6 }], result: 2 },
    crying_obsidian: { name: "Crying Obsidian", base_block: true },
    cut_copper: { name: "Cut Copper", ingredients: [{ id: "copper_block", quantity: 4 }], result: 4 },
    cut_copper_slab: { name: "Cut Copper Slab", ingredients: [{ id: "cut_copper", quantity: 3 }], result: 6 },
    cut_copper_stairs: { name: "Cut Copper Stairs", ingredients: [{ id: "cut_copper", quantity: 6 }], result: 4 },
    cut_red_sandstone: { name: "Cut Red Sandstone", ingredients: [{ id: "red_sandstone", quantity: 4 }], result: 4 },
    cut_red_sandstone_slab: {
        name: "Cut Red Sandstone Slab",
        ingredients: [{ id: "cut_red_sandstone", quantity: 3 }],
        result: 6,
    },
    cut_sandstone: { name: "Cut Sandstone", ingredients: [{ id: "sandstone", quantity: 4 }], result: 4 },
    cut_sandstone_slab: { name: "Cut Sandstone Slab", ingredients: [{ id: "cut_sandstone", quantity: 3 }], result: 6 },
    cyan_banner: {
        name: "Cyan Banner",
        ingredients: [
            { id: "cyan_wool", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 1,
    },
    cyan_bed: {
        name: "Cyan Bed",
        ingredients: [
            { id: "cyan_wool", quantity: 3 },
            { tag: "planks", quantity: 3 },
        ],
        result: 1,
    },
    cyan_candle: {
        name: "Cyan Candle",
        ingredients: [
            { id: "candle", quantity: 1 },
            { id: "cyan_dye", quantity: 1 },
        ],
        result: 1,
    },
    cyan_carpet: { name: "Cyan Carpet", ingredients: [{ id: "cyan_wool", quantity: 2 }], result: 3 },
    cyan_concrete: { name: "Cyan Concrete", ingredients: [{ id: "cyan_concrete_powder", quantity: 1 }], result: 1 },
    cyan_concrete_powder: {
        name: "Cyan Concrete Powder",
        ingredients: [
            { id: "cyan_dye", quantity: 1 },
            { id: "gravel", quantity: 4 },
            { id: "sand", quantity: 4 },
        ],
        result: 8,
    },
    cyan_glazed_terracotta: {
        name: "Cyan Glazed Terracotta",
        ingredients: [{ id: "cyan_terracotta", quantity: 1 }],
        result: 1,
    },
    cyan_shulker_box: {
        name: "Cyan Shulker Box",
        ingredients: [
            { id: "cyan_dye", quantity: 1 },
            { tag: "shulker_box", quantity: 1 },
        ],
        result: 1,
    },
    cyan_stained_glass: {
        name: "Cyan Stained Glass",
        ingredients: [
            { id: "cyan_dye", quantity: 1 },
            { id: "glass", quantity: 8 },
        ],
        result: 8,
    },
    cyan_stained_glass_pane: {
        name: "Cyan Stained Glass Pane",
        ingredients: [
            { id: "cyan_dye", quantity: 1 },
            { id: "glass_pane", quantity: 8 },
        ],
        result: 8,
    },
    cyan_terracotta: {
        name: "Cyan Terracotta",
        ingredients: [
            { id: "cyan_dye", quantity: 1 },
            { id: "terracotta", quantity: 8 },
        ],
        result: 8,
    },
    cyan_wool: {
        name: "Cyan Wool",
        ingredients: [
            { id: "cyan_dye", quantity: 1 },
            { tag: "wool", quantity: 1 },
        ],
        result: 1,
    },
    dandelion: { name: "Dandelion", base_block: true },
    dark_oak_button: { name: "Dark Oak Button", ingredients: [{ id: "dark_oak_planks", quantity: 1 }], result: 1 },
    dark_oak_door: { name: "Dark Oak Door", ingredients: [{ id: "dark_oak_planks", quantity: 6 }], result: 3 },
    dark_oak_fence: {
        name: "Dark Oak Fence",
        ingredients: [
            { id: "dark_oak_planks", quantity: 4 },
            { id: "stick", quantity: 2 },
        ],
        result: 3,
    },
    dark_oak_fence_gate: {
        name: "Dark Oak Fence Gate",
        ingredients: [
            { id: "dark_oak_planks", quantity: 2 },
            { id: "stick", quantity: 4 },
        ],
        result: 1,
    },
    dark_oak_hanging_sign: {
        name: "Dark Oak Hanging Sign",
        ingredients: [
            { id: "dark_oak_log", quantity: 6 },
            { id: "chain", quantity: 2 },
        ],
        result: 6,
    },
    dark_oak_leaves: { name: "Dark Oak Leaves", base_block: true },
    dark_oak_log: { name: "Dark Oak Log", base_block: true },
    dark_oak_planks: { name: "Dark Oak Planks", ingredients: [{ id: "dark_oak_log", quantity: 1 }], result: 4 },
    dark_oak_pressure_plate: {
        name: "Dark Oak Pressure Plate",
        ingredients: [{ id: "dark_oak_planks", quantity: 2 }],
        result: 1,
    },
    dark_oak_sapling: { name: "Dark Oak Sapling", base_block: true },
    dark_oak_sign: {
        name: "Dark Oak Sign",
        ingredients: [
            { id: "dark_oak_planks", quantity: 6 },
            { id: "stick", quantity: 1 },
        ],
        result: 3,
    },
    dark_oak_slab: { name: "Dark Oak Slab", ingredients: [{ id: "dark_oak_planks", quantity: 3 }], result: 6 },
    dark_oak_stairs: { name: "Dark Oak Stairs", ingredients: [{ id: "dark_oak_planks", quantity: 6 }], result: 4 },
    dark_oak_trapdoor: { name: "Dark Oak Trapdoor", ingredients: [{ id: "dark_oak_planks", quantity: 6 }], result: 2 },
    dark_oak_wood: { name: "Dark Oak Wood", ingredients: [{ id: "dark_oak_log", quantity: 4 }], result: 3 },
    dark_prismarine: {
        name: "Dark Prismarine",
        ingredients: [
            { id: "black_dye", quantity: 1 },
            { id: "prismarine_shard", quantity: 8 },
        ],
        result: 1,
    },
    dark_prismarine_slab: {
        name: "Dark Prismarine Slab",
        ingredients: [{ id: "dark_prismarine", quantity: 3 }],
        result: 6,
    },
    dark_prismarine_stairs: {
        name: "Dark Prismarine Stairs",
        ingredients: [{ id: "dark_prismarine", quantity: 6 }],
        result: 4,
    },
    daylight_detector: {
        name: "Daylight Detector",
        ingredients: [
            { id: "glass", quantity: 3 },
            { id: "nether_quartz", quantity: 3 },
            { tag: "wood_slabs", quantity: 3 },
        ],
        result: 1,
    },
    dead_brain_coral: { name: "Dead Brain Coral", base_block: true },
    dead_brain_coral_block: { name: "Dead Brain Coral Block", base_block: true },
    dead_brain_coral_fan: { name: "Dead Brain Coral Fan", base_block: true },
    dead_bubble_coral: { name: "Dead Bubble Coral", base_block: true },
    dead_bubble_coral_block: { name: "Dead Bubble Coral Block", base_block: true },
    dead_bubble_coral_fan: { name: "Dead Bubble Coral Fan", base_block: true },
    dead_bush: { name: "Dead Bush", base_block: true },
    dead_fire_coral: { name: "Dead Fire Coral", base_block: true },
    dead_fire_coral_block: { name: "Dead Fire Coral Block", base_block: true },
    dead_fire_coral_fan: { name: "Dead Fire Coral Fan", base_block: true },
    dead_horn_coral: { name: "Dead Horn Coral", base_block: true },
    dead_horn_coral_block: { name: "Dead Horn Coral Block", base_block: true },
    dead_horn_coral_fan: { name: "Dead Horn Coral Fan", base_block: true },
    dead_tube_coral: { name: "Dead Tube Coral", base_block: true },
    dead_tube_coral_block: { name: "Dead Tube Coral Block", base_block: true },
    dead_tube_coral_fan: { name: "Dead Tube Coral Fan", base_block: true },
    decorated_pot: {
        name: "Decorated Pot",
        ingredients: [{ id: "brick", quantity: 4 }],
        result: 1,
    },
    deepslate: { name: "Deepslate", base_block: true },
    deepslate_bricks: { name: "Deepslate Bricks", ingredients: [{ id: "polished_deepslate", quantity: 4 }], result: 4 },
    deepslate_brick_slab: {
        name: "Deepslate Brick Slab",
        ingredients: [{ id: "deepslate_bricks", quantity: 3 }],
        result: 6,
    },
    deepslate_brick_stairs: {
        name: "Deepslate Brick Stairs",
        ingredients: [{ id: "deepslate_bricks", quantity: 6 }],
        result: 4,
    },
    deepslate_brick_wall: {
        name: "Deepslate Brick Wall",
        ingredients: [{ id: "deepslate_bricks", quantity: 6 }],
        result: 6,
    },
    deepslate_coal_ore: { name: "Deepslate Coal Ore", base_block: true },
    deepslate_copper_ore: { name: "Deepslate Copper Ore", base_block: true },
    deepslate_diamond_ore: { name: "Deepslate Diamond Ore", base_block: true },
    deepslate_emerald_ore: { name: "Deepslate Emerald Ore", base_block: true },
    deepslate_gold_ore: { name: "Deepslate Gold Ore", base_block: true },
    deepslate_iron_ore: { name: "Deepslate Iron Ore", base_block: true },
    deepslate_lapis_ore: { name: "Deepslate Lapis Lazuli Ore", base_block: true },
    deepslate_redstone_ore: { name: "Deepslate Redstone Ore", base_block: true },
    deepslate_tiles: { name: "Deepslate Tiles", ingredients: [{ id: "deepslate_bricks", quantity: 4 }], result: 4 },
    deepslate_tile_slab: {
        name: "Deepslate Tile Slab",
        ingredients: [{ id: "deepslate_tiles", quantity: 3 }],
        result: 6,
    },
    deepslate_tile_stairs: {
        name: "Deepslate Tile Stairs",
        ingredients: [{ id: "deepslate_tiles", quantity: 6 }],
        result: 4,
    },
    deepslate_tile_wall: {
        name: "Deepslate Tile Wall",
        ingredients: [{ id: "deepslate_tiles", quantity: 6 }],
        result: 6,
    },
    detector_rail: {
        name: "Detector Rail",
        ingredients: [
            { id: "iron_ingot", quantity: 6 },
            { id: "redstone", quantity: 1 },
            { id: "stone_pressure_plate", quantity: 1 },
        ],
        result: 6,
    },
    diamond_block: { name: "Block of Diamond", ingredients: [{ id: "diamond", quantity: 9 }], result: 1 },
    diamond_ore: { name: "Diamond Ore", base_block: true },
    diorite: { name: "Diorite", base_block: true },
    diorite_slab: { name: "Diorite Slab", ingredients: [{ id: "diorite", quantity: 3 }], result: 6 },
    diorite_stairs: { name: "Diorite Stairs", ingredients: [{ id: "diorite", quantity: 6 }], result: 4 },
    diorite_wall: { name: "Diorite Wall", ingredients: [{ id: "diorite", quantity: 6 }], result: 6 },
});

/** @type {Object.<string, string[]}>} */
export const Tags = Object.freeze({
    cobblestone: ["blackstone", "cobblestone", "cobbled_deepslate"],
    planks: [
        "acacia_planks",
        "bamboo_planks",
        "birch_planks",
        "crimson_planks",
        "dark_oak_planks",
        "jungle_planks",
        "oak_planks",
        "spruce_planks",
        "warped_planks",
    ],
    shulker_box: [
        "black_shulker_box",
        "blue_shulker_box",
        "brown_shulker_box",
        "cyan_shulker_box",
        "gray_shulker_box",
        "green_shulker_box",
        "light_blue_shulker_box",
        "light_gray_shulker_box",
        "lime_shulker_box",
        "magenta_shulker_box",
        "orange_shulker_box",
        "pink_shulker_box",
        "purple_shulker_box",
        "red_shulker_box",
        "white_shulker_box",
        "yellow_shulker_box",
    ],
    wood_slabs: [
        "acacia_slab",
        "bamboo_slab",
        "birch_slab",
        "crimson_slab",
        "dark_oak_slab",
        "jungle_slab",
        "oak_slab",
        "spruce_slab",
        "warped_slab",
    ],
    // any wood, log, stem, and stripped variants
    wood: [
        "acacia_log",
        "acacia_wood",
        "birch_log",
        "birch_wood",
        "crimson_stem",
        "crimson_hyphae",
        "dark_oak_log",
        "dark_oak_wood",
        "jungle_log",
        "jungle_wood",
        "oak_log",
        "oak_wood",
        "spruce_log",
        "spruce_wood",
        "warped_stem",
        "warped_hyphae",
        "stripped_acacia_log",
        "stripped_acacia_wood",
        "stripped_birch_log",
        "stripped_birch_wood",
        "stripped_crimson_stem",
        "stripped_crimson_hyphae",
        "stripped_dark_oak_log",
        "stripped_dark_oak_wood",
        "stripped_jungle_log",
        "stripped_jungle_wood",
        "stripped_oak_log",
        "stripped_oak_wood",
        "stripped_spruce_log",
        "stripped_spruce_wood",
        "stripped_warped_stem",
        "stripped_warped_hyphae",
    ],
    wool: [
        "black_wool",
        "blue_wool",
        "brown_wool",
        "cyan_wool",
        "gray_wool",
        "green_wool",
        "light_blue_wool",
        "light_gray_wool",
        "lime_wool",
        "magenta_wool",
        "orange_wool",
        "pink_wool",
        "purple_wool",
        "red_wool",
        "white_wool",
        "yellow_wool",
    ],
});
